"""empty message

Revision ID: dd6407444951
Revises: 1cdb82e7f885
Create Date: 2018-02-04 20:04:23.005836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6407444951'
down_revision = '1cdb82e7f885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'posted')
    # ### end Alembic commands ###
