"""empty message

Revision ID: df6d094b2365
Revises: 26c9fffdf4da
Create Date: 2018-02-04 20:18:27.402913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6d094b2365'
down_revision = '26c9fffdf4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('commenter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'record', 'users', ['commenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'commenter_id')
    # ### end Alembic commands ###
